CREATE DATABASE IF NOT EXISTS Gosho_Kaloyan;

CREATE TABLE IF NOT EXISTS regions(
REGION_ID int,
REGION_NAME varchar(25),
PRIMARY KEY(REGION_ID)
);

CREATE TABLE IF NOT EXISTS countries(
COUNTRY_ID int,
COUNTRY_NAME varchar(40),
REGION_ID int,
PRIMARY KEY(COUNTRY_ID),
FOREIGN KEY (REGION_ID) REFERENCES regions(REGION_ID)
);

CREATE TABLE IF NOT EXISTS locations(
LOCATION_ID int,
STREET_ADDRESS varchar(25),
POSTAL_CODE varchar(12),
CITY varchar(30),
STATE_PROVINCE varchar(12),
COUNTRY_ID int,
PRIMARY KEY(LOCATION_ID),
FOREIGN KEY (COUNTRY_ID) REFERENCES countries(COUNTRY_ID)
);

CREATE TABLE IF NOT EXISTS departments(
DEPARTMENT_ID int,
DEPARTMENT_NAME varchar(30),
MANAGER_ID int,
LOCATION_ID int,
PRIMARY KEY(DEPARTMENT_ID),
FOREIGN KEY (LOCATION_ID) REFERENCES locations(LOCATION_ID)
);

CREATE TABLE IF NOT EXISTS job_history(
EMPLOYEE_ID int,
START_DATE date,
END_DATE date,
JOB_ID int,
DEPARTMENT_ID int,
PRIMARY KEY(EMPLOYEE_ID),
FOREIGN KEY (DEPARTMENT_ID) REFERENCES departments(DEPARTMENT_ID),
FOREIGN KEY (JOB_ID) REFERENCES jobs(JOB_ID)
);

CREATE TABLE IF NOT EXISTS employees(
EMPLOYEE_ID int,
FIRST_NAME varchar(20),
LAST_NAME varchar(25),
EMAIL varchar(40),
PHONE_NUMBER varchar(20),
HIRE_DATE date,
JOB_ID int,
SALARY int,
COMMISSION_PCT int,
MANAGER_ID int,
DEPARTMENT_ID int,
PRIMARY KEY(EMPLOYEE_ID),
FOREIGN KEY (EMPLOYEE_ID) REFERENCES job_history(EMPLOYEE_ID),
FOREIGN KEY (DEPARTMENT_ID) REFERENCES departments(DEPARTMENT_ID),
FOREIGN KEY (JOB_ID) REFERENCES jobs(JOB_ID)
);

CREATE TABLE IF NOT EXISTS jobs(
JOB_ID int,
JOB_TITLE varchar(35),
MIN_SALARY int,
MAX_SALARY int,
PRIMARY KEY(JOB_ID),
);

CREATE TABLE IF NOT EXISTS job_grades(
GRADE_LEVEL varchar(2),
LOWEST_SAL int,
HIGHEST_SAL int,
PRIMARY KEY(GRADE_LEVEL)
);